# Generated by Django 4.0.4 on 2022-05-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpslogRecord',
        ),
    ]
