# Generated by Django 4.0.4 on 2022-05-17 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_keyy_keyrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keyy',
            new_name='Key',
        ),
    ]
